DROP SCHEMA  IF EXISTS VLOG;

CREATE SCHEMA VLOG;
USE VLOG;


CREATE TABLE USER(
	USERNAME VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL
);


CREATE TABLE ARTICLE(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(20) NOT NULL,
	AUTHOR VARCHAR(20),
	CONTENT TEXT,
	FOREIGN KEY(AUTHOR) REFERENCES USER(USERNAME)
);

CREATE TABLE COMMENT(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CONTENT TEXT,
	USERNAME VARCHAR(20) NOT NULL ,
	ARTICLE_ID INT NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME),
	FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ID)
	
);